[tool.ruff]
line-length = 100

[tool.ruff.lint]
select=["ALL"]
extend-ignore=["D"]
ignore=[
    "D103", "D104", "D105", "D107",
    "FA102",
    "G004",
    "N812",
    "NPY002",
    "PD901",
    "PLW2901",
    "RET504",
    "RUF003",
    "S101", "S602",
    "T201",
]
