[tool.ruff]
line-length = 100

[tool.ruff.lint]
select=["ALL"]
extend-ignore=["ANN", "D", "ERA", "N"]
ignore=[
    "COM812",
    "D103", "D104", "D105", "D107",
    "E741",
    "FA102",
    "G004",
    "INP001",
    "N803", "N806", "N812",
    "NPY002",
    "PD901",
    "PLR0913", "PLR2004",
    "PLW2901",
    "RET504",
    "RUF003",
    "S101", "S602",
    "T201",
]
